### PR TITLE
Update memrepo.py

### PR DESCRIPTION
**Pull request by andreyfedoseev**

### CODE REVIEW

**Comment by lgiordani** [comment]
Hi! Thanks for the PR. Is there any particular reason for the change you propose? Thanks!

**Comment by andreyfedoseev** [comment]
Yeah, it catched my eye when you join the string and then split it in the case when no comparison operator is present in the filter. This join/split combo seems unnecessary.

**Comment by andreyfedoseev** [comment]
I also updated the `split` call to avoid an error in the case of `spam__ham__egg` filter.

**Comment by lgiordani** [comment]
Hey I'm sorry if you felt it was ignored. The repository is connected with a set of articles and it's always very difficult to update it. I didn't forget your PR purposefully, however

**Pull request closed without merging**
